"""
Setup model - Represents an Assetto Corsa car setup.
"""

from dataclasses import dataclass, field
from typing import Optional, Any
from datetime import datetime


@dataclass
class SetupSection:
    """Represents a section of a car setup (e.g., TYRES, BRAKES)."""
    
    name: str
    values: dict[str, Any] = field(default_factory=dict)
    
    def get(self, key: str, default: Any = None) -> Any:
        """Get a value from the section."""
        return self.values.get(key, default)
    
    def set(self, key: str, value: Any) -> None:
        """Set a value in the section."""
        self.values[key] = value
    
    def to_ini_format(self) -> str:
        """Convert section to INI format string."""
        lines = [f"[{self.name}]"]
        for key, value in self.values.items():
            lines.append(f"{key}={value}")
        return "\n".join(lines)


@dataclass
class Setup:
    """Represents a complete car setup for Assetto Corsa."""
    
    # Setup identification
    setup_id: Optional[int] = None
    name: str = "Generated Setup"
    
    # Associated car and track
    car_id: str = ""
    track_id: str = ""
    
    # Behavior used to generate this setup
    behavior: str = "balanced"
    
    # Setup sections
    sections: dict[str, SetupSection] = field(default_factory=dict)
    
    # Metadata
    created_at: datetime = field(default_factory=datetime.now)
    notes: str = ""
    
    # AI scoring data
    ai_score: float = 0.0
    ai_confidence: float = 0.0
    
    def __post_init__(self):
        """Initialize default sections if empty."""
        if not self.sections:
            self._initialize_default_sections()
    
    def _initialize_default_sections(self) -> None:
        """Create default setup sections with base values."""
        self.sections = {
            "TYRES": SetupSection("TYRES", {
                "PRESSURE_LF": 26.0,
                "PRESSURE_RF": 26.0,
                "PRESSURE_LR": 26.0,
                "PRESSURE_RR": 26.0
            }),
            "BRAKES": SetupSection("BRAKES", {
                "BIAS": 60.0,
                "FRONT_BIAS": 60.0,
                "BRAKE_POWER_MULT": 1.0
            }),
            "SUSPENSION": SetupSection("SUSPENSION", {
                # Front suspension
                "SPRING_RATE_LF": 80000,
                "SPRING_RATE_RF": 80000,
                "DAMP_BUMP_LF": 3000,
                "DAMP_BUMP_RF": 3000,
                "DAMP_REBOUND_LF": 5000,
                "DAMP_REBOUND_RF": 5000,
                # Rear suspension
                "SPRING_RATE_LR": 70000,
                "SPRING_RATE_RF": 70000,
                "DAMP_BUMP_LR": 2800,
                "DAMP_BUMP_RR": 2800,
                "DAMP_REBOUND_LR": 4500,
                "DAMP_REBOUND_RR": 4500,
                # Ride height
                "RIDE_HEIGHT_LF": 50,
                "RIDE_HEIGHT_RF": 50,
                "RIDE_HEIGHT_LR": 55,
                "RIDE_HEIGHT_RR": 55
            }),
            "DIFFERENTIAL": SetupSection("DIFFERENTIAL", {
                "POWER": 40.0,
                "COAST": 30.0,
                "PRELOAD": 20.0
            }),
            "ALIGNMENT": SetupSection("ALIGNMENT", {
                "CAMBER_LF": -3.0,
                "CAMBER_RF": -3.0,
                "CAMBER_LR": -2.0,
                "CAMBER_RR": -2.0,
                "TOE_LF": 0.0,
                "TOE_RF": 0.0,
                "TOE_LR": 0.1,
                "TOE_RR": 0.1
            }),
            "AERO": SetupSection("AERO", {
                "WING_FRONT": 0,
                "WING_REAR": 0
            }),
            "FUEL": SetupSection("FUEL", {
                "FUEL": 30
            }),
            "ARB": SetupSection("ARB", {
                "FRONT": 5,
                "REAR": 3
            })
        }
    
    def get_section(self, name: str) -> Optional[SetupSection]:
        """Get a setup section by name."""
        return self.sections.get(name)
    
    def set_value(self, section: str, key: str, value: Any) -> None:
        """Set a value in a specific section."""
        if section not in self.sections:
            self.sections[section] = SetupSection(section)
        self.sections[section].set(key, value)
    
    def get_value(self, section: str, key: str, default: Any = None) -> Any:
        """Get a value from a specific section."""
        if section not in self.sections:
            return default
        return self.sections[section].get(key, default)
    
    def has_value(self, section: str, key: str) -> bool:
        """Check if a value exists in a specific section."""
        if section not in self.sections:
            return False
        return key in self.sections[section].values
    
    def to_ini_string(self) -> str:
        """Convert entire setup to INI format string."""
        lines = [
            "; Generated by Race Engineer Assistant",
            f"; Car: {self.car_id}",
            f"; Track: {self.track_id}",
            f"; Behavior: {self.behavior}",
            f"; Created: {self.created_at.isoformat()}",
            ""
        ]
        
        for section in self.sections.values():
            lines.append(section.to_ini_format())
            lines.append("")
        
        return "\n".join(lines)
    
    def to_dict(self) -> dict:
        """Convert setup to dictionary for storage."""
        sections_dict = {}
        for name, section in self.sections.items():
            sections_dict[name] = section.values
        
        return {
            "setup_id": self.setup_id,
            "name": self.name,
            "car_id": self.car_id,
            "track_id": self.track_id,
            "behavior": self.behavior,
            "sections": sections_dict,
            "created_at": self.created_at.isoformat(),
            "notes": self.notes,
            "ai_score": self.ai_score,
            "ai_confidence": self.ai_confidence
        }
    
    @classmethod
    def from_dict(cls, data: dict) -> "Setup":
        """Create setup from dictionary."""
        sections = {}
        for name, values in data.get("sections", {}).items():
            sections[name] = SetupSection(name, values)
        
        created_at = data.get("created_at")
        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)
        elif created_at is None:
            created_at = datetime.now()
        
        return cls(
            setup_id=data.get("setup_id"),
            name=data.get("name", "Generated Setup"),
            car_id=data.get("car_id", ""),
            track_id=data.get("track_id", ""),
            behavior=data.get("behavior", "balanced"),
            sections=sections,
            created_at=created_at,
            notes=data.get("notes", ""),
            ai_score=data.get("ai_score", 0.0),
            ai_confidence=data.get("ai_confidence", 0.0)
        )
    
    def clone(self) -> "Setup":
        """Create a deep copy of this setup."""
        return Setup.from_dict(self.to_dict())
